---
title: "課堂練習"
date: "9/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("C:/Users/yofun/ANACON~1/envs/myEnvironment",
           required = T)
use_condaenv("myEnvironment", required = T)
```

```{python}
dictionaryA={
  "date": [2001,2002,2003],
  "price": [21000,33000,45880]}
dictionaryA

dictionaryA["number"]=[100,200,300]
dictionaryA
```

```{python}
dictionaryA.keys()
```

```{python}
dictionaryA.get("date")
dictionaryA.get("item")
dictionaryA.get("item","no this key") #last is warning word if no item key
```

```{python}
dictionaryA.keys()
dictionaryA.values()
dictionaryA.items()


list(dictionaryA.keys())
dictionaryA.keys()[0]
```

```{python}
dictionaryA.keys()

list(dictionaryA.keys())[1]
```

```{python}
list(dictionaryA.items())
```

```{python}
import pandas as pd
finStatement=pd.read_csv("http://mopsfin.twse.com.tw/opendata/t187ap06_O_ci.csv")
dict_finStatement=finStatement.to_dict()
```

```{r}
#library(dplyr)
View(py$dict_finStatement)
```

```{python}
dict_finStatement.keys()
```


```{python}
dict_finStatement.get( '營業利益（損失）').values()
dict_finStatement.get('公司名稱')
```

1. 找出損失的index
```{python}
profit=list(dict_finStatement.get( '營業利益（損失）').values())
lossFirmKeys=[index for index in range(len(profit)) if profit[index]<0]
```

2. 由index進去公司找出名稱
```{python}
index=lossFirmKeys[100]
dict_finStatement.get('公司名稱')[index]
dict_finStatement.get('公司名稱').get(index)
[dict_finStatement.get('公司名稱').get(index) for index in lossFirmKeys]
```

dictionary comprehension 呈現公司名稱：損失金額
```{python}
{dict_finStatement.get('公司名稱').get(index): list(dict_finStatement.get( '營業利益（損失）').values())[index] for index in lossFirmKeys}
```

```{python}
dict_finStatement.get( '營業利益（損失）').values()
```


# comprehension with condition

```{python}
listA=[10,2,7,3,8]
[listA[index] for index in range(len(listA)) if listA[index]>5]
[index for index in range(len(listA)) if listA[index]>5 ]
```

```{python}
def test(input1, input2=0):
  print('input1 is ', input1)
  print('input2 is ', input2)
  return None
  
test(1,1) 
test(input1=1,input2=1)

test(1) # 
```

## pack to tuple

```{python}
def test2(input1,*input3):
  print('input1 is ', input1)
  print('input3 is ', input3)
  return None
 
test2(1,1.2,4,5)
test2(1,[1.2,4],5)
test2(["1","b"],{2,5,7},10)
```

```{python}
def test3(input1,**input4):
  print('input1 is ', input1)
  print('input4 is ', input4)
  return None
 
test3(1,a=10,b={2,3})
```


```{python}
input1, *input3=(1, 1.2, 4, 5)
input1, *input3=(1,[1.2,4],5)
input1, *input3=(["1","b"],{2,5,7},10)
```

```{python}
x, *seq, y=(1,2,3,4,5)
```

```{python}
def f(x, *seq, y):
    print("x is: ", x)
    print("seq is: ", seq)
    print("y is: ", y)
    return None
f(1, 2, 3, 4, 5) #why?
f(1, 2, 3, 4, y=5)
```

```{python}
def f(a,b,c):
   return a+b+c


f(1,3,4)
f(*[1,3],4)
f(1,*[3,4])
f(*[1,3,4])
```


```{python}
a, b, c=(1,3,4)
a, b, c=(*[1,3],4)
a, b, c=(1,*[3,4])
a, b, c=(*[1,3,4])
```

```{python}
from math import *

def normal_pdf(z,mu,sigma):
  return 1/(sqrt(2*pi*sigma**2))*exp(-(z-mu)**2/(2*sigma**2))

normal_pdf(0.8,0,1)
```


```{python}
def utility_cobb_douglass(x,y,alpha=1,beta=3):
  
  utilValue = x**alpha*y**beta # 程序產生output值
  
  return utilValue # 傳回output值

utility_cobb_douglass(1,1,0.5,0.5)
utility_cobb_douglass(1,1)

```

```{python}
x, y, **parameters  =(1,1,alpha=0.5,beta=0.5)
```

```{python}
parameters={
"alpha": 0.5,
"beta": 0.5
}
```



```{python}
x, y, **parameters  =(1,1,alpha=0.5,beta=0.5)
parameters={
"alpha": 0.5,
"beta": 0.5
}
def utility_cobb_douglas(x, y, **parameters):
  alpha=parameters["alpha"]
  beta=parameters["beta"]
  utilValue = x**alpha*y**beta 
  return utilValue # 傳回output值
```

# local global environment

```{python}
obj2
obj3
::
::
# call objX=utility_cobb_douglass(1,1,alpha=0.5,beta=0.5)
  x,y,alpha,beta=(1,1,0.5,0.5)
  utilValue = x**alpha*y**beta 
  return utilValue
```

```{python}
global1=[1,3,[4,5]]
def funtest(x):
  x[0]="a"
  y=x[:]
  y[1]="b"
  y[2][1]="c"
  return None
global1
funtest(global1) #call
global1
```

# executive environment of funtest(global1)
```{python}
global1=[1,3,[4,5]]
global1
# enter executive environment
x=global1
x[0]="a"
y=x[:]
y[1]="b"
y[2][1]="c"
# kill executive environment objects
del x, y
global1
```


```{python}
global1=[1,3,[4,5]]
def funtest(x):
  x[0]="a"
  y=x[:]
  y[1]="b"
  y[2][1]="c"
  return None
global1
funtest(global1)
global1
```


```{python}
def utility_cobb_douglass(x,y,alpha=1,beta=3):
  
  utilValue = x**alpha*y**beta*obj3 # 程序產生output值
  
  return utilValue # 傳回output值
utility_cobb_douglass(1,1,0.5,0.5)
utility_cobb_douglass(1,1)
```



```{python}
global1=[1,3,[4,5]]
funtest(global1.copy())
global1
import copy 
global1=[1,3,[4,5]]
funtest(copy.deepcopy(global1))
global1
```


```{python}
def test(x,y):
  return x+y+obj3
obj3=5
test(1,4)
```