---
title: "課堂練習"
date: "9/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("C:/Users/yofun/ANACON~1/envs/myEnvironment",
           required = T)
use_condaenv("myEnvironment", required = T)
```

```{r}
library(reticulate)
conda_create("myEnvironment")
```

```{r}
# conda安裝方式
conda_install("myEnvironment", # 沙盒環境名稱
              c("numpy","pandas")) # 要安裝的modules
```

```{python}
dictionaryA ={"name": "Mary", "id": "A28374", "grade": 77}
dictionaryA

{key: dictionaryA[key] for key in ['name','grade']} # dictionary comprehension
```

```{python}
setB = {
1: "a", 
2: "c",
"3": 2,  
4: 3,
5: 7
}

setB["3"]
```

```{python}
sparseMatrix = {
(0, 0): 3, 
(0, 2): -2, 
(0, 3): 11,
(1, 1): 9, 
(2, 1): 7, 
(3, 3): -5}
print(sparseMatrix)

sparseMatrix[(1, 1)]
```

```{python}
listA = [2, 3, 4, 7, 6]
listA[2] = -1 #can change
listA
```

```{python}
grade = {
(172, "小明"): 80,
(214, "大雄"): 60,
(322, "胖虎"): 90,
(425, "小新"): 70,
(517, "大白"): 50
}

(172, "小明")
```
```{python}
grade = {
"id": [172, 214, 322, 425, 517],
"name": ["a","b","c","d","e"],
"scores": [80,60,90,70,50]
}
```

```{python}
grade["scores"]
```

```{python}
grade["name"][0]
grade["scores"][0]
{grade["name"][0]: grade["scores"][0]}
```
```{python}
{
grade['name'][i]: grade["grades"][i] for i in [0, 1, 2, 3, 4]
}
```

```{python}
sparseMatrix = {
(0, 0): 3, 
(0, 2): -2, 
(0, 3): 11,
(1, 1): 9, 
(2, 1): 7, 
(3, 3): -5}
print(sparseMatrix)
```

```{python}
dictionaryA={
"name": "amy",
"age": 33
}
dictionaryA["name"]="amyy"
dictionaryA
```

```{python}
listA=[2,7,5,-2,13]
listA[0] = 0
listA[1] = ("a", "b")
listA
```



```{python}
originalList=[1,2,"a"]
definitionCopy=originalList 
sliceCopy=originalList[:] 
sliceCopy2=originalList.copy()
sliceCopy
sliceCopy2
```

```{python}
print(definitionCopy)
print(originalList)

definitionCopy[1]="b"
print(definitionCopy)
print(originalList)

originalList[1]=2
print(definitionCopy)
print(originalList)
```

切割式複製則不會完全相依。
```{python}
originalList=[1,2,"a"]
sliceCopy=originalList[:] # slice copy
print(sliceCopy)
print(originalList)

sliceCopy[1]="b"
print(sliceCopy)
print(originalList)

originalList[1]="f"
print(sliceCopy)
print(originalList)
```

```{python}
originalList=[1,2,10]
listA=originalList+[5,7] # concatenate
listB=originalList*2 # duplicate

print(originalList)
print(listA)
print(listB)

originalList[0]=0
print(originalList)
print(listA)
print(listB)
```


```{python}
treeA=[1,2,3,[4,5],[6,7]]

treeACopy = treeA.copy()
```
```{python}
listA=[2,3,"b"]
listA.append(5)
listA #  change (mutable)
stringA="Hello"
stringA.upper()
stringA # no change (immutable)
```

```{python}
nestedList=[1,2,[3,4,[5,6]],[7,8]]
copy1=nestedList[:]
print(nestedList)

# 
nestedList[1]="d"
print(nestedList)
print(copy1)

# 
nestedList[3][1]="leave"
print(nestedList)
print(copy1)
```


```{python}
3>4
a=3
b=4
c=5
a; b; c
```
```{python}
numList=[3,2,11,43]
[numList[i] + 3 for i in [0, 1, 2, 3]]
```

```{python}
[numList[i] > 10 for i in [0, 1, 2, 3]]
```

```{python}
a="Hello, how are you?"
len(a) # 
b=["Hello"]
len(b) # 
```

```{python}
x = "Hello " + "World"
x
y = "wow..."*3
y
x
x[0:5]
```

```{python}
listB=["A","B","C"]
listC=[1.,2.,3.]
listB+listC
listB*3
```


```{python}
x=[1,2,3]
y=[1,2,3]
z=[1,2]
x==y #yes
x==z
x is x 
x is y #no
```
```{python}
5 in [1,5,3]
[5] in [1,5,3]

5 in [[1],[5],[3]]
[5] in [[1],[5],[3]]
```

```{python}
x = set([1, 2, 3, 1, 3, 5]) 
x
# {1, 2, 3, 5}  
3 in x
```


```{python}
listF=[2,5,10,11,-1,7]
listG=[4,7,-2,10,11,15]
[listF[i] > listG[i] for i in [0, 1, 2, 3, 4, 5]]
```

```{python}
listC=[2,3,4]
[str(listC[i]) for i in [0, 1, 2]]

str(2)
```

```{python}
list2iter=["a",2,"c"]
[i for i in [0,1,2]]
[i for i in range(0,3)] 
[i for i in range(0,len(list2iter))] 

[type(list2iter[i]) is str for i in range(0,3)]
```

```{python}
"{0}'s {1} scores is {2}".format("Amy", "Econ", 50)  
"{}'s {} scores is {}".format("Amy", "Econ", 50) 
"{1}'s {0} scores is {2}".format("Econ","Amy", 50)   


"{name}'s {subject} scores is {grade}".format(
  name="Amy",grade=50,subject="Econ") 
```