---
title: "homework1"
output: html_document
params:
  studentID: "710761103"
  studentName: "張又方"
---
# 注意事項

存檔與填寫注意事項：

假設你叫王小明，學號41078392。

  1. 存檔時，請用你的學號當延伸檔名。學號為41078392，則請存成hwX-41078392.Rmd, X為這次作業號碼。(記得使用：File > save with enconding, 然後選utf-8)

  2. 本文檔開始的Frontmatter中，studentID（即key）其value目前為"你的學號"，以上面學號為例則必需改成"41078392"；而studentName（key）其value目前為"你的名字"，以上面名字為例則必需改成"王小明"

# 題目

請先執以下code chunk開啟RStudio底下的Python環境：

  * 注意`use_python`的路徑及`use_condaenv`的沙盒環境必需改成你電腦的對應設定。
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=F)

library(reticulate)
use_python("C:/Users/yofun/ANACON~1/envs/myEnvironment",required = T)
use_condaenv("myEnvironment", required = T)
```

## 作答需知

  * 每一題會有設好的ans chunk，請將你的程式寫在裡面，切勿自行加新的python chunk。
  
  * 每一題都需要你把答案存在指定的物件，並在「**最後一行**」打物件名稱。以下例，若答案是`2+3`並要你存在答案物件test裡，那你的程式如下：
```{python}
test = 2+3 # 答案存在指定test物件
test # 最後一行打指定物件名稱
```

  * 以下每個ans chunk的最後一行有#號mark起來是指定答案物件的名字，請將你運算答案存在該物件，並把最後一行的#號拿掉。

## 1 
執行以下程序隨機產生一個有12個數字的list x。
```{python data1}
import random
x=[random.randint(0,100) for i in range(0,12)]
x
```

### 1.1 class轉換
取出x的第一個元素並將它轉成字串存在答案物件`x0_str`.
```{python ans11}
x0_str = x[0]
x0_str
```

### 1.2 list comprehension
將x由整數list轉成每個元素值皆為字串的字串list，存在答案物件`x_str`。（必需用到list comprehension）
```{python ans12}
x_str = [str(x[i]) for i in [0,1,2,3,4,5,6,7,8,9,10,11]]
x_str
```

### 1.3 邏輯判斷
取出x的第七個元素，判斷它是否小於50（小於為True）存在答案物件`x6_logi`
```{python ans13}
x6_logi = x[6]<50
x6_logi
```

### 1.4 邏輯判斷+list comprehension
產生`x_logi`邏輯判斷list，原個元素為x對應元素是否小於50的邏輯判斷結果（小於為True)
```{python ans14}
x_logi = [x[i]<50 for i in [0,1,2,3,4,5,6,7,8,9,10,11]]
x_logi
```

### 1.5 邏輯運算
計算x_logi中False的個數，存在答案物件`num_false`。 （
```{python ans15}
listA = []
for i in range(len(x)):
 if x[i]>50:
  listA = listA.append(i)
# num_false
```

## 2
執行以下程序得到2019年8月公司設立登記清冊（source: <https://data.gov.tw/dataset/6047>），以dictionary class存在dict_business裡
```{python data2}
import pandas as pd
df_business=pd.read_csv("http://data.gcis.nat.gov.tw/od/file?oid=340B4FDD-880E-4287-9289-F32782F792B8")
dict_business=df_business.to_dict()
```

### 2.1 
有多少公司的'公司所在地'在'桃園市'，請將數字存在`num_taoyuan`。

```{python ans21}
listB = list(dict_business['公司所在地'])
listB.count('桃園市')
# num_taoyuan
```

### 2.2
有多少公司的'資本額'大於500000，請將數字存在`num_largeCapital`。
```{python ans22}
listC = [dict_business["資本額"][i]  
  for i in range(len(dict_business["資本額"] )) 
  if dict_business["資本額"][i] > 500000]
num_largeCapital = len(listC)
num_largeCapital
```

## 3
請先在r裡使用`conda_install()`安裝requests模組，接著執行以下程序得到台灣2019年不同舞蹈的表演資訊danceInfo。
```{python data3}
import requests
response=requests.get("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3")
danceInfo=response.json()
```

### 3.1
danceInfo的每個元素是一場表演的訊息，請找出它有多少場舞蹈表演，存在numDance的class int物件裡
```{python ans31}
numDance = len(danceInfo) #???
numDance
```

### 3.2
第1場的表演名稱'title'是什麼？請存在名為title1的物件裡。
```{python ans32}
danceInfo['title']
# title1
```


### 3.3
第1場的表演地點'location'在哪裡?請存在名為local1的物件裡。

```{python ans33}
# local1
```

### 3.4
第1場的表演時間'time'為何？請存在名為time11的物件裡。

```{python ans34}
# time1
```

### 3.5
產生一個長度與表演個數一樣的list，稱為danceInfoList，每個元素是一個表演的訊息，以dictionary形式記錄分別以'title','time'及'location'為key，其value為該表演的對應資訊。例如：`print(danceInfoList[0:2])`會出現

[{'title': '原音舞絢', 'time': '2019/09/29 14:30:00', 'location': '台北市中山南路21號，藍白建築1樓'}, {'title': '國立彰化生活美學館108年「舞藝人生-土風舞藝術」推廣計畫-第四場', 'time': '2019/11/03 08:30:00', 'location': '彰化縣彰化市卦山路18號'}]

```{python ans35}
# danceInfoList
```

### 3.6
產生一個list of string, 對應每一場演出它會形成如下的陳述句，以上題danceInfo[0]的資訊為例，它的陳述句為：
'【原音舞絢】將於2019/09/29 14:30:00在台北市中山南路21號，藍白建築1樓演出'

```{python ans36}
# danceInfoStr
```
